// Code generated by goctl. DO NOT EDIT.

export interface AccountAddBackReply {
	id: number
}

export interface AccountAddBackReq {
	admin_id: number // admin_id
	ct_user_id: number // csgo tools id
	account_name: string // steam账户名
	cookie: string // cookie内容
	status: number // 状态：1->正常；2->禁用；
}

export interface AccountChangeStatusBackReply {
}

export interface AccountChangeStatusBackReq {
	id: number // id
	status: 1 | 2 // 启用状态；2->禁用；1->启用
}

export interface AccountDeleteBackReply {
}

export interface AccountDeleteBackReq {
}
export interface AccountDeleteBackReqParams {
}

export interface AccountGetBackReply {
}

export interface AccountGetBackReq {
}
export interface AccountGetBackReqParams {
}

export interface AccountListBackReply {
	total: number // 总条数
	list: Array<PmsAccount> // 列表
}

export interface AccountListBackReq {
}
export interface AccountListBackReqParams {
	admin_id?: number // admin_id
	ct_user_id?: number // csgo tools id
	account_name?: string // steam账户名
	status?: number // 启用状态：2->禁用；1->启用
	page: number // 页码
	pageSize: number // 每页大小
}

export interface AccountOkBackReply {
}

export interface AccountUpdateBackReply {
}

export interface AccountUpdateBackReq {
	id?: number // id
	admin_id: number // admin_id
	ct_user_id: number // csgo tools id
	account_name: string // steam账户名
	cookie: string // cookie内容
	status: number // 状态：1->正常；2->禁用；
}

export interface AccountUpsertBackReply {
}

export interface AccountUpsertBackReq {
	account_name: string // steam账户名
	cookie: string // cookie内容
}

export interface AdminAddBackReply {
	id: number
}

export interface AdminAddBackReq {
	id?: number // id
	username?: string // 用户名
	password?: string // 密码
	nickname?: string // 昵称
	avatar?: string // 头像
	mobile?: string // 手机号
	isSuper?: number // 是否超级管理员：2->不是；1->是
	roleIds?: Array<number> // role ids
}

export interface AdminChangePasswordBackReq {
	oldPassword: string // 旧密码
	password: string // 密码
}

export interface AdminChangeStatusReq {
	id: number // id
	status: 1 | 2 // 启用状态；2->禁用；1->启用
}

export interface AdminGetBackReq {
}
export interface AdminGetBackReqParams {
}

export interface AdminListBackReply {
	total: number // 总条数
	list: Array<SysAdmin> // 列表
}

export interface AdminListBackReq {
}
export interface AdminListBackReqParams {
	username?: string // 用户名
	nickname?: string // 昵称
	mobile?: string // 手机号
	roleId?: number // 角色id
	isSuper?: number // 是否超级管理员：2->不是；1->是
	status?: number // 启用状态：2->禁用；1->启用
	page: number // 页码
	pageSize: number // 每页大小
}

export interface AdminLogListBackReply {
	total: number // 总条数
	list: Array<SysAdminLog> // 列表
}

export interface AdminLogListBackReq {
}
export interface AdminLogListBackReqParams {
	username?: string // 用户名
	mobile?: string // 手机号
	roleId?: number // 角色id
	roleName?: string // 角色名称
	startTime?: string // 开始时间
	endTime?: string // 结束时间
	page: number // 页码
	pageSize: number // 每页大小
}

export interface AdminLoginBackReply {
	admin: SysAdmin
}

export interface AdminLoginBackReq {
	username: string // 用户名
	password: string // 密码
	captchaId?: string // id
	captchaValue?: string // 验证码
}

export interface AdminLoginSimpleBackReq {
	username: string // 用户名
}

export interface AdminMenuListBackReply {
	list: Array<SysMenu> // 列表
}

export interface AdminMenuListBackReq {
}

export interface AdminMobileLoginBackReq {
	mobile: string // 手机号
	captcha: string // 验证码
}

export interface AdminOkBackReply {
}

export interface ArticleAddBackReq {
	id?: number
	categoryId?: number // 分类ID
	categoryCode?: string // 分类code
	code?: string // 文章标识码
	title?: string // 文章标签
	thumb?: string // 文章缩略图
	summary?: string // 文章摘要
	content?: string // 文章内容
	link?: string // 链接地址
	relation_type?: number // 关联类型 1 链接 2 营销活动 3 富文本
	relation?: string // 关联信息
	sort?: number // 排序
	status?: number // 启用状态；2->禁用；1->启用
}

export interface ArticleChangeStatusBackReq {
	id: number // id
	status: 1 | 2 // 启用状态；2->禁用；1->启用
}

export interface ArticleDeleteBackReq {
	id?: number // id
	code?: string // 或分类code
}

export interface ArticleGetBackReq {
}
export interface ArticleGetBackReqParams {
	id?: number // id
	code?: string // 或分类code
}

export interface ArticleGetFrontReq {
}
export interface ArticleGetFrontReqParams {
	id?: number // id
	code?: string // 或分类code
	show_read_status?: number // 是否显示阅读状态；其他->不显示；1->显示
}

export interface ArticleListBackReply {
	total: number // 总条数
	list: Array<CmsArticle> // 列表
}

export interface ArticleListBackReq {
}
export interface ArticleListBackReqParams {
	categoryId?: number // 分类ID
	categoryCode?: string // 分类code
	title?: string // 标题
	code?: string // 或分类code
	status?: number // 启用状态：2->禁用；1->启用
	page: number // 页码
	pageSize: number // 每页大小
}

export interface ArticleListFrontReply {
	total: number // 总条数
	list: Array<CmsArticle> // 列表
}

export interface ArticleListFrontReq {
}
export interface ArticleListFrontReqParams {
	categoryId?: number // 分类ID
	categoryCode?: string // 或分类code
	title?: string // 标题
	code?: string // 或文章code
	show_read_status?: number // 是否显示阅读状态；其他->不显示；1->显示
	page: number // 页码
	pageSize: number // 每页大小
}

export interface ArticleOkBackReply {
}

export interface ArticleReadFrontReply {
}

export interface ArticleReadFrontReq {
	id: number // 文章id
}

export interface ArticleUnreadNumberFrontReply {
	number: number // 未读数量
}

export interface ArticleUnreadNumberFrontReq {
}
export interface ArticleUnreadNumberFrontReqParams {
	categoryCode?: string // 或分类code
}

export interface CaptchaGetMathMixReply {
	captchaId: string // id
	captchaImg: string // base64图片内容
}

export interface CaptchaGetMathMixReq {
}

export interface CaptchaGetTextMixReply {
	captchaId: string // id
	captchaImg: string // base64图片内容
}

export interface CaptchaGetTextMixReq {
}

export interface CaptchaVerifyMixReply {
	success: boolean
}

export interface CaptchaVerifyMixReq {
}
export interface CaptchaVerifyMixReqParams {
	captchaId: string // id
	captchaValue: string // 验证码
}

export interface CategoryAddBackReq {
	id: number
	parentId?: number // 父级ID
	parentCode?: string // 父级code
	name: string // 分类名称
	code?: string // 分类code
	desc: string // 描述
	status: number // 启用状态：2->禁用；1->启用
}

export interface CategoryChangeStatusReq {
	id: number // id
	status: 1 | 2 // 启用状态；2->禁用；1->启用
}

export interface CategoryGetBackReq {
}
export interface CategoryGetBackReqParams {
}

export interface CategoryGetFrontReq {
}
export interface CategoryGetFrontReqParams {
	id?: number // id
	code?: string // 或分类code
}

export interface CategoryListBackReply {
	total: number // 总条数
	list: Array<CmsCategory> // 列表
}

export interface CategoryListBackReq {
}
export interface CategoryListBackReqParams {
	parentId?: number // 父级ID
	parentCode?: string // 父级分类code
	code?: string // 分类code
	name?: string // 分类名称
	status?: number // 启用状态：2->禁用；1->启用
	page: number // 页码
	pageSize: number // 每页大小
}

export interface CategoryListLevelBackReply {
	list: Array<CmsCategory> // 列表
}

export interface CategoryListLevelBackReq {
}

export interface CategoryOkBackReply {
}

export interface CategorySubFrontReply {
	list: Array<CmsCategory> // 子列表
}

export interface CategorySubFrontReq {
}
export interface CategorySubFrontReqParams {
	parentId?: number // 父级ID
	parentCode?: string // 父级Code
}

export interface ChangePasswordFrontReq {
	password: string // 用户登录密码
	captcha: string // 短信验证码
}

export interface CloseFrontReq {
	safe_password: string // 用户支付密码
}

export interface CmsArticle {
	id: number
	categoryId: number // 分类ID
	code: string // 文章标识码
	title: string // 文章标题
	thumb: string // 文章缩略图
	summary: string // 文章摘要
	content: string // 文章内容
	link: string // 链接地址
	relation_type: number // 关联类型 1 链接 2 营销活动 3 富文本
	relation: string // 关联信息
	sort: number // 排序
	status: number // 启用状态；2->禁用；1->启用
	is_read: number // 是否已读 1已读 2未读
	createTime: string // 创建时间
	updateTime: string // 更新时间
}

export interface CmsCategory {
	id: number
	parentId: number // 父级ID
	name: string // 分类名称
	code: string // 分类code
	desc: string // 描述
	status: number // 启用状态：2->禁用；1->启用
	createTime: string // 创建时间
	list: Array<CmsCategory> // 子列表
}

export interface CmsRead {
	id: number
	user_id: number // 所属创作者ID
	category_id: number // 分类id
	object_type: number // 已读数据类型
	object_id: number // 已读数据id
}

export interface ConfigGetReq {
}
export interface ConfigGetReqParams {
}

export interface ConfigListBackReply {
	total: number // 总条数
	list: Array<SysConfig> // 列表
}

export interface ConfigListBackReq {
}
export interface ConfigListBackReqParams {
	category?: string // 分类
	name?: string // 配置名称
	key?: string // 配置key
	page: number // 页码
	pageSize: number // 每页大小
}

export interface ConfigOkBackReply {
}

export interface ConfigSetBackReq {
	category?: string // 分类
	name?: string // 配置名称
	key: string // 配置key
	value: string // 配置值
	desc?: string // 描述
}

export interface ConfigSetsBackReq {
	list: Array<ConfigSetBackReq> // 配置列表
}

export interface CurrentAccountBackReq {
}

export interface CurrentAdminBackReq {
}

export interface CurrentAdminUpdateBackReq {
	nickname: string // 昵称
	avatar: string // 头像
}

export interface DictGetFrontReq {
}
export interface DictGetFrontReqParams {
}

export interface DictGetReq {
}
export interface DictGetReqParams {
}

export interface DictListBackReply {
	total: number // 总条数
	list: Array<SysDict> // 列表
}

export interface DictListBackReq {
}
export interface DictListBackReqParams {
	parentId?: number // 父级ID
	parent_code?: string // 父级Code
	code?: string // 字典名称
	page: number // 页码
	pageSize: number // 每页大小
}

export interface DictListFrontReply {
	total: number // 总条数
	list: Array<SysDict> // 列表
}

export interface DictListFrontReq {
}
export interface DictListFrontReqParams {
	parentId?: number // 父级ID
	parent_code?: string // 父级Code
	code?: string // 字典名称
	page: number // 页码
	pageSize: number // 每页大小
}

export interface DictOkBackReply {
}

export interface DictSetBackReq {
	id?: number
	parentId: number // 父级ID
	code: string // 字典code
	value: string // 字典名称或值
	desc: string // 描述
	sort: number // 字典排序
}

export interface FeebackAddFrontReply {
}

export interface FeebackAddFrontReq {
	question: string // 反馈问题
	images: string // 图片
}

export interface FeedbackListBackReply {
	total: number // 总条数
	list: Array<UmsFeedback> // 列表
}

export interface FeedbackListBackReq {
}
export interface FeedbackListBackReqParams {
	user_id?: number // 用户id
	reply_status?: number // 状态
	start_time?: string // 开始时间
	end_time?: string // 结束时间
	page: number // 页码
	pageSize: number // 每页大小
}

export interface FeedbackListFrontReply {
	total: number // 总条数
	list: Array<UmsFeedback> // 列表
}

export interface FeedbackListFrontReq {
}
export interface FeedbackListFrontReqParams {
	page: number // 页码
	pageSize: number // 每页大小
}

export interface FeedbackReplyBackReply {
}

export interface FeedbackReplyBackReq {
	id: number // id
	reply: string // 回复内容
}

export interface JwtTokenBack {
	accessToken?: string
	accessExpire?: number
	refreshAfter?: number
}

export interface JwtTokenFront {
	accessToken?: string
	accessExpire?: number
	refreshAfter?: number
}

export interface LoginFrontReply {
	user: UmsUser
}

export interface LoginFrontReq {
	username: string
	password: string
}

export interface LoginMobileFrontReq {
	mobile: string // 手机号
	captcha: string // 短信验证码
	inviter_code?: string // 邀请人code
}

export interface LoginPasswordFrontReq {
	mobile: string // 手机号
	password: string // 密码
	captchaId?: string // 验证码id
	captchaValue?: string // 验证码
}

export interface LoginProfileFrontReq {
	avatar?: string // 头像
	nickname: string // 用户昵称
}

export interface MenuAddBackReq {
	id: number
	parentId: number // 父级ID
	title: string // 菜单名称
	level: number // 菜单级数
	sort: number // 菜单排序
	name: string // 前端名称
	icon: string // 前端图标
	path: string // 前端url路径
	status: number // 启用状态；2->禁用；1->启用
}

export interface MenuChangeStatusReq {
	id: number // id
	status: 1 | 2 // 启用状态；2->禁用；1->启用
}

export interface MenuGetBackReq {
}
export interface MenuGetBackReqParams {
}

export interface MenuListBackReply {
	total: number // 总条数
	list: Array<SysMenu> // 列表
}

export interface MenuListBackReq {
}
export interface MenuListBackReqParams {
	parentId?: number // 父级ID
	level?: number // 菜单级数
	name?: string // 名称
	status: number // 启用状态；2->禁用；1->启用
	page: number // 页码
	pageSize: number // 每页大小
}

export interface MenuListLevelBackReply {
	list: Array<SysMenu> // 列表
}

export interface MenuListLevelBackReq {
}

export interface MenuOkBackReply {
}

export interface OssStsMixReply {
	AccessKeySecret: string
	Expiration: string
	AccessKeyId: string
	SecurityToken: string
	Endpoint: string
	Bucket: string
}

export interface OssStsMixReq {
}

export interface PermissionAddBackReq {
	id?: number // id 有则编辑,无则新增
	parentId: number // 父级权限id
	name: string // 名称
	value: string // 权限值
	status: number // 启用状态；2->禁用；1->启用
	sort: number // 菜单排序
}

export interface PermissionChangeStatusReq {
	id: number // id
	status: 1 | 2 // 启用状态；2->禁用；1->启用
}

export interface PermissionGetBackReq {
}
export interface PermissionGetBackReqParams {
}

export interface PermissionListBackReply {
	total: number // 总条数
	list: Array<SysPermission> // 列表
}

export interface PermissionListBackReq {
}
export interface PermissionListBackReqParams {
	parentId?: number // 父级权限id
	name?: string // 名称
	value?: string // 权限值
	status: number // 启用状态；2->禁用；1->启用
	page: number // 页码
	pageSize: number // 每页大小
}

export interface PermissionListLevelBackReply {
	list: Array<SysPermission> // 列表
}

export interface PermissionListLevelBackReq {
}

export interface PermissionOkBackReply {
}

export interface PmsAccount {
	id: number // ID
	admin_id: number // admin_id
	ct_user_id: number // csgo tools id
	account_name: string // steam账户名
	password: string // steam密码
	steam_id: string // steam id
	api_key: string // steam api key
	login_type: string // 登录方式 maFile/shared_secret/cookie
	mafile: string // mafile json内容
	cookie: string // cookie内容
	shared_secret: string // shared_secret
	currency: number // 货币类型，默认1 美元账户
	status: number // 状态：1->正常；2->禁用；
	steam_valid_status: number // steam配置有效状态：1->未验证 2->验证中 3->正常；4->不正确
	steam_invalid_desc: string // steam配置无效原因
	create_time: string // 创建时间
	update_time: string // 更新时间
}

export interface ProfileFrontReq {
	avatar: string // 头像
	nickname: string // 用户昵称
	intro: string // 用户简介
	bg: string // 用户背景图
}

export interface RealNameFrontReq {
	real_name: string // 真实姓名
	id_card: string // 身份证号
}

export interface RegisterFrontReq {
	username: string // 用户名
	password: string // 用户密码
	mobile: string // 手机号
	nickname: string // 用户昵称
	avatar: string // 头像
}

export interface ReportAddFrontReply {
}

export interface ReportAddFrontReq {
	report_type: number // 投诉对象类型
	report_id: number // 投诉内容id
	question_type?: number // 问题类型
	title: string // 信息标题
	question: string // 投诉问题
}

export interface ReportListBackReply {
	total: number // 总条数
	list: Array<UmsReport> // 列表
}

export interface ReportListBackReq {
}
export interface ReportListBackReqParams {
	user_id?: number // 用户id
	report_type?: number // 投诉对象类型
	report_id?: number // 投诉内容id
	question_type?: number // 投诉类型
	reply_status?: number // 状态 1 待处理 2 不予处理 3 冻结作品 4 沟通用户
	start_time?: string // 开始时间
	end_time?: string // 结束时间
	page: number // 页码
	pageSize: number // 每页大小
}

export interface ReportReplyBackReply {
}

export interface ReportReplyBackReq {
	id: number // id
	reply: string // 回复内容
	reply_status: number // 状态 1 待处理 2 不予处理 3 冻结作品 4 沟通用户
}

export interface RoleAddBackReq {
	id: number // id
	name: string // 名称
	description: string // 描述
	status: number // 启用状态：2->禁用；1->启用
	sort: number // 排序
}

export interface RoleBindMenuBackReq {
	id: number // id
	menuIds?: Array<number> // 菜单
}

export interface RoleBindPermissionBackReq {
	id: number // id
	permissionIds?: Array<number> // 权限
}

export interface RoleChangeStatusReq {
	id: number // id
	status: 1 | 2 // 启用状态；2->禁用；1->启用
}

export interface RoleGetBackReq {
}
export interface RoleGetBackReqParams {
}

export interface RoleListBackReply {
	total: number // 总条数
	list: Array<SysRole> // 列表
}

export interface RoleListBackReq {
}
export interface RoleListBackReqParams {
	name?: string // 名称
	status: number // 启用状态；2->禁用；1->启用
	page: number // 页码
	pageSize: number // 每页大小
}

export interface RoleMenusBackReply {
	list: Array<SysMenu> // 菜单列表
}

export interface RoleMenusBackReq {
}
export interface RoleMenusBackReqParams {
	roleId: number // id
}

export interface RoleOkBackReply {
}

export interface RolePermissionsBackReply {
	list: Array<SysPermission> // 权限列表
}

export interface RolePermissionsBackReq {
}
export interface RolePermissionsBackReqParams {
	roleId: number // id
}

export interface SafePasswordFrontReq {
	safe_password: string // 用户支付密码
	captcha: string // 短信验证码
}

export interface SmsSendMixReply {
}

export interface SmsSendMixReq {
}
export interface SmsSendMixReqParams {
	mobile: string // 手机号
	captchaId?: string // 验证码id
	captchaValue?: string // 验证码value
}

export interface SmsUserSendMixReq {
}
export interface SmsUserSendMixReqParams {
	mobile?: string // id
}

export interface SysAdmin {
	id: number // id
	username: string // 用户名
	password: string // 密码
	nickname: string // 昵称
	avatar: string // 头像
	mobile: string // 手机号
	isSuper: number // 是否超级管理员：2->不是；1->是
	status: number // 启用状态：2->禁用；1->启用
	loginTime: string // 最后登录时间
	createTime: string // 创建时间
	roles: Array<SysRole> // 角色
	roleIds: Array<number> // role ids
}

export interface SysAdminLog {
	id: number
	admin_id: number // 管理员id
	admin_username: string // 姓名
	operation: string // 用户操作
	content: string // 操作详情
	ip: string // ip地址
	create_time: string // 创建时间
	admin: SysAdmin
}

export interface SysConfig {
	id: number
	category: string // 分类
	name: string // 配置名称
	key: string // 配置key
	value: string // 配置值
	desc: string // 描述
	createTime: string // 创建时间
}

export interface SysDict {
	id: number
	parentId: number // 父级ID
	code: string // 字典code
	value: string // 字典名称或值
	desc: string // 描述
	sort: number // 字典排序
	createTime: string // 创建时间
	dicts: Array<SysDict> // 子字典
}

export interface SysMenu {
	id: number
	parentId: number // 父级ID
	title: string // 菜单名称
	level: number // 菜单级数
	sort: number // 菜单排序
	name: string // 前端名称
	icon: string // 前端图标
	path: string // 前端url路径
	status: number // 启用状态；2->禁用；1->启用
	createTime: string // 创建时间
	menus: Array<SysMenu> // 子菜单
}

export interface SysPermission {
	id: number
	parentId: number // 父级权限id
	name: string // 名称
	value: string // 权限值
	status: number // 启用状态；2->禁用；1->启用
	sort: number // 菜单排序
	createTime: string // 创建时间
	permissions: Array<SysPermission>
}

export interface SysRole {
	id: number
	name: string // 名称
	description: string // 描述
	status: number // 启用状态：2->禁用；1->启用
	sort: number // 排序
	createTime: string // 创建时间
	permissions: Array<SysPermission> // 权限
	menus: Array<SysMenu> // 角色
}

export interface UmsFeedback {
	id: number
	user_id: number // 反馈用户id
	question: string // 问题
	images: string // 4张图片
	reply: string // 回复内容
	reply_status: number // 状态 1 是 2 否
	reply_time: string // 回复时间
	admin_id: number // 管理员id
	create_time: string // 创建时间
	user: UmsUser
	admin: SysAdmin
}

export interface UmsReport {
	id: number
	user_id: number // 用户id
	report_type: number // 投诉对象类型
	report_id: number // 投诉内容id
	question_type: number // 问题类型
	title: string // 信息标题
	question: string // 投诉问题
	status: number // 启用状态：2->未处理；1->已处理
	reply: string // 回复内容
	reply_status: number // 状态 1 待处理 2 不予处理 3 冻结作品 4 沟通用户
	reply_time: string // 回复时间
	admin_id: number // 管理员id
	create_time: string // 创建时间
	user: UmsUser
	report_user: UmsUser
}

export interface UmsUser {
	id: number // 用户ID
	username: string // 用户名
	mobile: string // 手机号
	nickname: string // 用户昵称
	avatar_asset_id: number // 头像资产id
	avatar: string // 头像
	inviter_code: string // 邀请人code
	inviter_id: number // 邀请人
	real_name: string // 真实姓名
	id_card: string // 身份证号
	real_name_status: number // 实名状态
	open_status: number // 开户状态 1开 2未开
	register_ip: string // 注册IP
	status: number // 启用状态：2->禁用；1->正常; 3->注销
	is_safe_password: number // 安全密码设置状态：2->否；1->是
	create_time: string // 创建时间
	update_time: string // 更新时间
	extend: UmsUserExtend // 用户扩展信息
}

export interface UmsUserExtend {
	id: number // ID
	user_id: number // 用户id
	intro: string // 用户简介
	bg: string // 用户背景图
}

export interface UmsUserFollow {
	id: number // ID
	user_id: number // 用户id
	follow_user_id: number // 关注的用户id
	status: number // 关注状态 启用状态：2->未关注；1->关注
}

export interface UmsUserFollowSimple {
	id: number // 用户ID
	nickname: string // 用户昵称
	avatar: string // 头像
	status: number // 0 未关注 1 已关注 2 被关注 3 已互相关注 4 自己
}

export interface UmsUserInfo {
	id: number // 用户ID
	nickname: string // 用户昵称
	avatar: string // 头像
	follow_count: number // 我关注人数
	fans_count: number
	extend: UmsUserExtend // 用户扩展信息
}

export interface UmsUserInvite {
	id: number // ID
	nickname: string // 用户昵称
	avatar: string // 头像
	invite_count: number // 邀请数量统计
	create_time: string // 创建时间
}

export interface UmsUserNotice {
	id: number // ID
	user_id: number // 用户id
	title: string // 标题
	content: string // 内容
	level: number // 消息级别 1普通 2重要
	is_read: number // 是否已读 1已读 2未读
	read_time: string // 已读时间
	create_time: string // 创建时间
}

export interface UmsUserSimple {
	id: number // 用户ID
	nickname: string // 用户昵称
	avatar: string // 头像
}

export interface UserChangePasswordReply {
}

export interface UserChangePasswordReq {
	id: number // id
	password: string // 密码
}

export interface UserChangeRealNameStatusReply {
}

export interface UserChangeRealNameStatusReq {
	id: number // id
	status: number // 启用状态
}

export interface UserChangeStatusReply {
}

export interface UserChangeStatusReq {
	id: number // id
	status: 1 | 2 | 3 // 启用状态；2->禁用；1->启用 3注销
}

export interface UserDetailFrontReplay {
	user: UmsUser
}

export interface UserDetailFrontReq {
}

export interface UserFrontReply {
}

export interface UserGetBackReq {
}
export interface UserGetBackReqParams {
}

export interface UserInfoFrontReq {
}
export interface UserInfoFrontReqParams {
}

export interface UserInviteListFrontReply {
	total: number // 总条数
	list: Array<UmsUserInvite> // 列表
}

export interface UserInviteistFrontReq {
}
export interface UserInviteistFrontReqParams {
	page: number // 页码
	pageSize: number // 每页大小
}

export interface UserListBackReply {
	total: number // 总条数
	list: Array<UmsUser> // 列表
}

export interface UserListBackReq {
}
export interface UserListBackReqParams {
	id?: number // 用户id
	mobile?: string // 手机号
	nickname?: string // 用户昵称
	real_name?: string // 真实姓名
	real_name_status?: number // 实名状态
	status?: number // 启用状态：2->禁用；1->正常; 3->注销
	start_time?: string // 开始时间
	end_time?: string // 结束时间
	page: number // 页码
	pageSize: number // 每页大小
}

export interface UserListFrontReply {
	total: number // 总条数
	list: Array<UmsUserSimple> // 列表
}

export interface UserListFrontReq {
}
export interface UserListFrontReqParams {
	nickname?: string // 用户昵称
	start_time?: string // 开始时间
	end_time?: string // 结束时间
	page: number // 页码
	pageSize: number // 每页大小
}

export interface UserMyInviteListFrontReply {
	total: number // 总条数
	list: Array<UmsUserInvite> // 列表
}

export interface UserMyInviteistFrontReq {
}
export interface UserMyInviteistFrontReqParams {
	nickname?: string
	start_time?: string // 开始时间
	end_time?: string // 结束时间
	page: number // 页码
	pageSize: number // 每页大小
}

export interface UserNoticeDeleteFrontReply {
}

export interface UserNoticeDeleteFrontReq {
	id: number // id
}

export interface UserNoticeEmptyFrontReply {
}

export interface UserNoticeEmptyFrontReq {
}

export interface UserNoticeListFrontReply {
	total: number // 总条数
	list: Array<UmsUserNotice> // 列表
}

export interface UserNoticeListFrontReq {
}
export interface UserNoticeListFrontReqParams {
	page: number // 页码
	pageSize: number // 每页大小
}

export interface UserNoticeReadAllFrontReply {
}

export interface UserNoticeReadAllFrontReq {
}

export interface UserNoticeReadFrontReply {
}

export interface UserNoticeReadFrontReq {
	id: number // id
}

export interface UserNoticeSendFrontReply {
}

export interface UserNoticeSendFrontReq {
	title: string // 标题
	content: string // 内容
}

export interface UserNoticeUnreadNumberFrontReply {
	number: number // 未读数量
}

export interface UserNoticeUnreadNumberFrontReq {
}

